apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-akv-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: akv-wp-test        # Set to the name of your key vault
    
    objects:  |
      array:
        - |
          objectName: wp-db-pass
          objectType: secret              # object types: secret, key, or cert
    tenantId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secretObjects:                             
  - secretName: dbsecrets   
    data:
    - key: wp-db-pass                          
      objectName: wp-db-pass                                        
    type: Opaque   
